### PR TITLE
add a SetOutput function for the global logger object.

### PR DESCRIPTION
**Pull request by chasinglogic**
Feel free to just cherry pick the relevant commit, not sure why I had to merge instead of fast-forward but didn't feel like re-forking.

### CODE REVIEW

**Comment by rdeusser** [comment]
Hi @chasinglogic! Do you mind moving this code to `logsip.go` instead? It would more at home there. Other than that, I'd be happy to accept this. Thanks! 👍

**Comment by rdeusser** [comment]
Also, I didn't realize my global git config was wrong so I had to reset my author which I know is typically recommended against, but this isn't a super huge project and not a whole lot of people work on this so it should be fine.

**Comment by chasinglogic** [comment]
I will go ahead and refork then put the fix where you requested and resubmit the pull request

**Comment by rdeusser** [comment]
Thank you!

**Pull request closed without merging**
